version: '3.7'

volumes:
  database: ~

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  php-fpm:
    build:
      context: docker/php
      args:
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
    volumes:
      - .:/var/www:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 7777:7777
    environment:
      PHP_IDE_CONFIG: "serverName=local"
      XDEBUG_MODE: "develop,debug,trace"
      XDEBUG_CONFIG: "client_host=${XDEBUG_HOST:-host.docker.internal} client_port=${XDEBUG_PORT:-9000} start_with_request=yes log='/var/www/log/xdebug.log' cli_color=1"