<?php

namespace Lib\Database;

class QueryBuilderDeleter extends QueryBuilderUpdater
{
    /**
     * Не использовать !!!! Т.к данный билдер только удалеят записи из БД и не умеет обновлять или добавлять записи
     * @param string $column
     * @param int|string $value
     * @return QueryBuilderUpdater
     */
    public function set(string $column, $value): QueryBuilderUpdater
    {
        return parent::set($column, $value); // TODO: Change the autogenerated stub
    }

    public function getQuery(): string
    {
        return sprintf('DELETE FROM %s WHERE %s', $this->tableName, $this->queryWhere);
    }
}